name: ChromFoundBench
channels:
  - defaults
  - nvidia
  - pytorch
  - conda-forge
  - bioconda
dependencies:
  - python=3.10.19
  - pip=25.2
  - ipykernel
  - jupyter
  - conda-pack
  # Note: cuda-toolkit must be installed separately from nvidia channel (see README step 2)
  - pyyaml=6.0.2
  - yaml=0.2.5
  - numpy=1.26.4
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - pip:
      - scipy==1.15.3
      - scanpy==1.10.4
      - episcanpy==0.3.1
      - tqdm
      - tensorboardx==2.6.2.2
      - wandb==0.23.0